trigger: none

pool:
  name: Linux-agent

stages:
  - stage:
    displayName: "Terraform Plan & Apply"
    jobs:
      - job:
        displayName: "Terraform Plan and Destroy"
        steps:
          - task: TerraformInstaller@1
            displayName: "Terraform install"
            inputs:
              terraformVersion: "latest"
          - task: TerraformTaskV4@4
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "DunDon Free Subcription(cfd7c513-8b41-4dc8-b1ed-69bad9822f7d)"
              backendAzureRmResourceGroupName: "tfstate-rg"
              backendAzureRmStorageAccountName: "motormatetf"
              backendAzureRmContainerName: "tfstate"
              backendAzureRmKey: "terraform.tfstate"
          - task: TerraformTaskV4@4
            displayName: "Terraform Plan"
            inputs:
              provider: "azurerm"
              command: "plan"
              commandOptions: "--destroy"
              environmentServiceNameAzureRM: "DunDon Free Subcription(cfd7c513-8b41-4dc8-b1ed-69bad9822f7d)"
          - task: TerraformTaskV4@4
            displayName: "Terraform Destroy"
            inputs:
              provider: "azurerm"
              command: "destroy"
              commandOptions: "--auto-approve"
              environmentServiceNameAzureRM: "DunDon Free Subcription(cfd7c513-8b41-4dc8-b1ed-69bad9822f7d)"
